using System;

namespace Backbone.Menus
{
    public class MenuOptionSlider : IMenuItem
    {

        public int ID { get; set; }
        public string Name { get; set; }
        public int Minimum { get; set; }
        public int Maximum { get; set; }
        public int StepAmount { get; set; }
        public int Value { get; set; }

        public int DefaultValue { get; internal set; }

        public Action<int> OnChange { get; set; } = null;
        public MenuItemType Type { get; set; } = MenuItemType.OptionSlider;
        public bool IsSelected { get; set; } = false;

        public bool CanPrev
        {
            get
            {
                return Value > Minimum;
            }
        }

        public bool CanNext
        {
            get
            {
                return Value < Maximum;
            }
        }

        public MenuOptionSlider(string name, int min, int max, int step)
        {
            Name = name;
            Minimum = min;
            Maximum = max;
            StepAmount = step;
            Value = min;
        }

        /// <summary>
        /// Sets the default value after we verify it's a valid option and not a mistake the coder made.
        /// If it can't be a valid option generated by the slider, then throw an exception to let the coder know.
        /// </summary>
        /// <param name="defaultValue"></param>
        public void SetDefaultValue(int defaultValue)
        {
            bool found = false;
            for(var i = Minimum; i <= Maximum; i+=StepAmount)
            {
                if(i == defaultValue)
                {
                    found = true;
                    break;
                }
            }

            if(found)
            {
                DefaultValue = defaultValue;
                Value = DefaultValue;
            }
            else
            {
                throw new Exception(string.Format("Provided default value of {0} is not a valid option for MenuOptionSlider {1}", defaultValue, Name));
            }
        }

        public void Next()
        {
            var oldValue = Value;
            Value = Math.Min(Maximum, Value + StepAmount);

            if (Value != oldValue && OnChange != null)
            {
                OnChange.Invoke(Value);
            }
        }

        public void Prev()
        {
            var oldValue = Value;
            Value = Math.Max(Minimum, Value - StepAmount);

            if(Value != oldValue && OnChange != null)
            {
                OnChange.Invoke(Value);
            }
        }

        public void Click()
        {
            throw new NotImplementedException();
        }
    }
}
