using System;

namespace Backbone.Menus
{
    public class MenuOptionSlider : IMenuItem
    {

        public int ID { get; set; }
        public string Name { get; set; }
        public string DisplayText { get; set; }
        public int Minimum { get; set; }
        public int Maximum { get; set; }
        public int StepAmount { get; set; }
        public int Value { get; set; }

        public int DefaultValue { get; internal set; }

        public Action<int> OnChange { get; set; } = null;
        public MenuItemType Type { get; set; } = MenuItemType.OptionSlider;
        public bool IsSelected { get; set; } = false;
        public bool WrapAround { get; set; } = false;

        public bool CanPrev
        {
            get
            {
                return Value > Minimum || WrapAround;
            }
        }

        public bool CanNext
        {
            get
            {
                return Value < Maximum || WrapAround;
            }
        }

        public MenuOptionSlider(string name, string displayText, int min, int max, int step)
        {
            Name = name;
            DisplayText = displayText;
            Minimum = min;
            Maximum = max;
            StepAmount = step;
            Value = min;
        }

        /// <summary>
        /// Sets the default value after we verify it's a valid option and not a mistake the coder made.
        /// If it can't be a valid option generated by the slider, then throw an exception to let the coder know.
        /// </summary>
        /// <param name="defaultValue"></param>
        public void SetDefaultValue(int defaultValue)
        {
            bool found = false;
            for(var i = Minimum; i <= Maximum; i+=StepAmount)
            {
                if(i == defaultValue)
                {
                    found = true;
                    break;
                }
            }

            if(found)
            {
                DefaultValue = defaultValue;
                Value = DefaultValue;
            }
            else
            {
                throw new Exception(string.Format("Provided default value of {0} is not a valid option for MenuOptionSlider {1}", defaultValue, Name));
            }
        }

        public void Next()
        {
            var oldValue = Value;
            Value = WrapAround ?
                (Value + StepAmount > Maximum) ? 
                    Minimum :
                    Value + StepAmount :
                Math.Min(Maximum, Value + StepAmount);

            if (Value != oldValue && OnChange != null)
            {
                OnChange.Invoke(Value);
            }
        }

        public void Prev()
        {
            var oldValue = Value;
            Value = WrapAround ? 
                (Value - StepAmount < Minimum) ? 
                    Maximum : 
                    Value - StepAmount :
                Math.Max(Minimum, Value - StepAmount);

            if(Value != oldValue && OnChange != null)
            {
                OnChange.Invoke(Value);
            }
        }

        public void Click()
        {
            // don't do anything
        }

        public void SetValue(object value)
        {
            Value = (int)value;
        }

        public object GetValue()
        {
            return Value;
        }

        public IMenuItem GetByName(string name)
        {
            return (this.Name == name) ? this : null;
        }
    }
}
